-- Crank #2 seed data: entity identity rows only, big six vendors.
-- No claims, no prose. Values taken from vendors' own public crawler docs,
-- verified by direct HTTP fetch of each ip_list_url on 2026-09-13.
-- See /home/claude/crank2-site/NOTES.md for the full source list and
-- the two vendors where a field was deliberately left NULL.

INSERT OR IGNORE INTO entities
  (slug, vendor, name, kind, purpose, ua_token, ua_pattern, robots_token, ip_list_url, docs_url, first_documented, first_seen_here, last_seen_here, status, notes, created_at, updated_at)
VALUES
  ('gptbot', 'OpenAI', 'GPTBot', 'crawler', 'training',
   'GPTBot', 'GPTBot', 'GPTBot',
   'https://openai.com/gptbot.json',
   'https://platform.openai.com/docs/bots',
   '2026-09-13', NULL, NULL, 'active',
   'Crawls public web content for OpenAI model training. Respects robots.txt per vendor documentation.',
   '2026-09-13T00:00:00Z', '2026-09-13T00:00:00Z'),

  ('oai-searchbot', 'OpenAI', 'OAI-SearchBot', 'search_bot', 'search',
   'OAI-SearchBot', 'OAI-SearchBot', 'OAI-SearchBot',
   'https://openai.com/searchbot.json',
   'https://platform.openai.com/docs/bots',
   '2026-09-13', NULL, NULL, 'active',
   'Surfaces web pages in ChatGPT search results. Respects robots.txt per vendor documentation.',
   '2026-09-13T00:00:00Z', '2026-09-13T00:00:00Z'),

  ('chatgpt-user', 'OpenAI', 'ChatGPT-User', 'fetcher', 'user_fetch',
   'ChatGPT-User', 'ChatGPT-User', 'ChatGPT-User',
   'https://openai.com/chatgpt-user.json',
   'https://platform.openai.com/docs/bots',
   '2026-09-13', NULL, NULL, 'active',
   'Fetches a page only when a ChatGPT or Custom GPT user directs it to that URL. Vendor documentation states robots.txt rules may not apply to this fetcher.',
   '2026-09-13T00:00:00Z', '2026-09-13T00:00:00Z'),

  ('oai-adsbot', 'OpenAI', 'OAI-AdsBot', 'ads_bot', 'ads',
   'OAI-AdsBot', 'OAI-AdsBot', 'OAI-AdsBot',
   'https://openai.com/adsbot.json',
   'https://platform.openai.com/docs/bots',
   '2026-09-13', NULL, NULL, 'active',
   'Checks ad landing page quality and relevance for ChatGPT ads. Vendor documentation states it only visits pages submitted for ads review.',
   '2026-09-13T00:00:00Z', '2026-09-13T00:00:00Z'),

  ('claudebot', 'Anthropic', 'ClaudeBot', 'crawler', 'training',
   'ClaudeBot', 'ClaudeBot', 'ClaudeBot',
   'https://claude.com/crawling/bots.json',
   'https://support.claude.com/en/articles/8896518-does-anthropic-crawl-content-from-the-web-and-how-can-site-owners-block-the-crawler',
   '2026-09-13', NULL, NULL, 'active',
   'Collects web content that may contribute to Anthropic model training. Respects robots.txt per vendor documentation.',
   '2026-09-13T00:00:00Z', '2026-09-13T00:00:00Z'),

  ('claude-searchbot', 'Anthropic', 'Claude-SearchBot', 'search_bot', 'search',
   'Claude-SearchBot', 'Claude-SearchBot', 'Claude-SearchBot',
   'https://claude.com/crawling/bots.json',
   'https://support.claude.com/en/articles/8896518-does-anthropic-crawl-content-from-the-web-and-how-can-site-owners-block-the-crawler',
   '2026-09-13', NULL, NULL, 'active',
   'Navigates the web to improve Claude search result quality. Respects robots.txt per vendor documentation.',
   '2026-09-13T00:00:00Z', '2026-09-13T00:00:00Z'),

  ('claude-user', 'Anthropic', 'Claude-User', 'fetcher', 'user_fetch',
   'Claude-User', 'Claude-User', 'Claude-User',
   'https://claude.com/crawling/bots.json',
   'https://support.claude.com/en/articles/8896518-does-anthropic-crawl-content-from-the-web-and-how-can-site-owners-block-the-crawler',
   '2026-09-13', NULL, NULL, 'active',
   'Retrieves a page when a Claude user directs Claude to access that URL. Respects robots.txt per vendor documentation.',
   '2026-09-13T00:00:00Z', '2026-09-13T00:00:00Z'),

  ('perplexitybot', 'Perplexity', 'PerplexityBot', 'search_bot', 'search',
   'PerplexityBot', 'PerplexityBot', 'PerplexityBot',
   'https://www.perplexity.ai/perplexitybot.json',
   'https://docs.perplexity.ai/docs/resources/perplexity-crawlers',
   '2026-09-13', NULL, NULL, 'active',
   'Surfaces and links websites in Perplexity search results. Respects robots.txt per vendor documentation.',
   '2026-09-13T00:00:00Z', '2026-09-13T00:00:00Z'),

  ('perplexity-user', 'Perplexity', 'Perplexity-User', 'fetcher', 'user_fetch',
   'Perplexity-User', 'Perplexity-User', 'Perplexity-User',
   'https://www.perplexity.ai/perplexity-user.json',
   'https://docs.perplexity.ai/docs/resources/perplexity-crawlers',
   '2026-09-13', NULL, NULL, 'active',
   'Fetches a page when a Perplexity user asks a question that requires that page. Vendor documentation states this fetcher generally ignores robots.txt rules.',
   '2026-09-13T00:00:00Z', '2026-09-13T00:00:00Z'),

  ('googlebot', 'Google', 'Googlebot', 'crawler', 'search',
   'Googlebot', 'Googlebot', 'Googlebot',
   'https://developers.google.com/static/crawling/ipranges/common-crawlers.json',
   'https://developers.google.com/crawling/docs/crawlers-fetchers/google-common-crawlers',
   '2026-09-13', NULL, NULL, 'active',
   'Common crawler for Google Search, Discover, Images, Video and News. Respects robots.txt per vendor documentation.',
   '2026-09-13T00:00:00Z', '2026-09-13T00:00:00Z'),

  ('googleother', 'Google', 'GoogleOther', 'crawler', 'mixed',
   'GoogleOther', 'GoogleOther', 'GoogleOther',
   'https://developers.google.com/static/crawling/ipranges/common-crawlers.json',
   'https://developers.google.com/crawling/docs/crawlers-fetchers/google-common-crawlers',
   '2026-09-13', NULL, NULL, 'active',
   'Generic crawler used by various Google product teams to fetch publicly accessible content outside Search. Respects robots.txt per vendor documentation.',
   '2026-09-13T00:00:00Z', '2026-09-13T00:00:00Z'),

  ('google-extended', 'Google', 'Google-Extended', 'policy_token', 'training',
   NULL, NULL, 'Google-Extended',
   NULL,
   'https://developers.google.com/crawling/docs/crawlers-fetchers/google-common-crawlers',
   '2026-09-13', NULL, NULL, 'active',
   'Robots.txt token that controls whether content already crawled by Googlebot may be used to train Gemini models and ground Gemini features. Vendor documentation states Google-Extended is not a separate crawler and uses no distinct user agent string: it cannot be observed directly in request logs, only declared for in robots.txt.',
   '2026-09-13T00:00:00Z', '2026-09-13T00:00:00Z'),

  ('bingbot', 'Microsoft', 'Bingbot', 'crawler', 'search',
   'bingbot', 'bingbot', 'bingbot',
   'https://www.bing.com/toolbox/bingbot.json',
   'https://www.bing.com/webmasters/help/which-crawlers-does-bing-use-8c184ec0',
   '2026-09-13', NULL, NULL, 'active',
   'Crawls the web for Bing Search and, per Microsoft, feeds Copilot and Bing Chat surfaces. Respects robots.txt. Microsoft documents a separate opt-out from generative-AI training use via the noarchive robots meta tag or X-Robots-Tag header rather than a distinct Copilot user agent; no Copilot-specific crawler token is named in Microsoft''s public documentation as of 2026-09-13.',
   '2026-09-13T00:00:00Z', '2026-09-13T00:00:00Z'),

  ('applebot', 'Apple', 'Applebot', 'crawler', 'search',
   'Applebot', 'Applebot(?!-Extended)', 'Applebot',
   'https://search.developer.apple.com/applebot.json',
   'https://support.apple.com/en-us/119829',
   '2026-09-13', NULL, NULL, 'active',
   'Crawls the web to power Siri, Spotlight and Safari search features. Respects robots.txt and adjusts crawl rate automatically per vendor documentation.',
   '2026-09-13T00:00:00Z', '2026-09-13T00:00:00Z'),

  ('applebot-extended', 'Apple', 'Applebot-Extended', 'policy_token', 'training',
   NULL, NULL, 'Applebot-Extended',
   NULL,
   'https://support.apple.com/en-us/119829',
   '2026-09-13', NULL, NULL, 'active',
   'Robots.txt token that controls whether content already crawled by Applebot may be used to train Apple foundation models. Vendor documentation states Applebot-Extended does not crawl web pages: it is a policy token, not an observable crawler.',
   '2026-09-13T00:00:00Z', '2026-09-13T00:00:00Z');
