#!/usr/bin/env python3
"""Generate the Worker's data modules from site/content (no bundler).

  content/*.md          -> src/content.js  (policy pages, as strings)
  content/lint-rules.json -> src/lint.js   (voice lint rules + lintText())
  content/site.css      -> src/css.js      (served at /assets/site.css)

Run from anywhere; deploy.sh runs it before every upload. The generated
files are committed so a reader can see exactly what ships.
"""
import hashlib
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SITE = os.path.dirname(HERE)
CONTENT = os.path.join(SITE, "content")
SRC = os.path.join(SITE, "src")

HEADER = "// GENERATED by tools/gen-modules.py from site/content. Do not edit by hand.\n"


def write(name, body):
    with open(os.path.join(SRC, name), "w") as f:
        f.write(HEADER + body)


def gen_content():
    pages = {}
    for slug in ["about", "methodology", "corrections", "editorial-policy"]:
        with open(os.path.join(CONTENT, slug + ".md")) as f:
            text = f.read().replace("—", ", ")
        pages[slug] = text
    body = "export const POLICY_PAGES = " + json.dumps(pages, indent=1, ensure_ascii=False) + ";\n"
    body += "export const POLICY_VERSION = " + json.dumps(
        hashlib.sha256(json.dumps(pages, sort_keys=True).encode()).hexdigest()[:12]) + ";\n"
    write("content.js", body)


def gen_css():
    with open(os.path.join(CONTENT, "site.css")) as f:
        css = f.read().replace("—", "-").replace("–", "-")
    extra = os.path.join(CONTENT, "site-extra.css")
    if os.path.exists(extra):
        with open(extra) as f:
            css += "\n" + f.read()
    body = "export const SITE_CSS = " + json.dumps(css, ensure_ascii=False) + ";\n"
    body += "export const SITE_CSS_VERSION = " + json.dumps(hashlib.sha256(css.encode()).hexdigest()[:10]) + ";\n"
    write("css.js", body)


LINT_FUNCS = r'''
function escapeRe(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

const PHRASE_RES = [
  ...LINT_RULES.banned.map((b) => ({ phrase: b.phrase, kind: "banned", replacement: b.replacement })),
  ...LINT_RULES.quotation_only.map((p) => ({ phrase: p, kind: "quotation_only", replacement: null })),
].map((r) => ({ ...r, re: new RegExp(`(^|[^\\p{L}\\p{N}])${escapeRe(r.phrase).replace(/'/g, "['’]")}(?=$|[^\\p{L}\\p{N}])`, "iu") }));

// Removes the spans the rules never lint: text inside straight or curly
// double quotation marks, Markdown blockquote lines, exempt names.
export function stripVerbatim(text, exemptTerms = []) {
  let t = String(text || "");
  t = t.split("\n").filter((l) => !/^\s*>/.test(l)).join("\n");
  t = t.replace(/"[^"\n]*"/g, "\"\"").replace(/“[^”]*”/g, "“”");
  for (const e of [...LINT_RULES.exempt, ...exemptTerms]) {
    if (!e) continue;
    t = t.replace(new RegExp(escapeRe(e), "gi"), " ");
  }
  return t;
}

// Returns a list of {phrase, kind, replacement} hits for the site's own
// words in `text`. An empty list means the text passes. A banned phrase
// that contains a quotation_only word is reported once, as the phrase.
export function lintText(text, { exemptTerms = [] } = {}) {
  const hits = [];
  const raw = String(text || "");
  const own = stripVerbatim(raw, exemptTerms);
  if (/—/.test(own)) hits.push({ phrase: "—", kind: "em_dash", replacement: "full stop, colon, parentheses or a pair of commas" });
  if (/―/.test(own)) hits.push({ phrase: "―", kind: "dash", replacement: "full stop or colon" });
  if (/–/.test(own)) hits.push({ phrase: "–", kind: "en_dash", replacement: "'to' for ranges" });
  if (/\S -- \S/.test(own)) hits.push({ phrase: " -- ", kind: "dash", replacement: "full stop or colon" });
  if (/\S - \S/.test(own)) hits.push({ phrase: " - ", kind: "dash", replacement: "full stop or colon" });
  const banned = [];
  for (const r of PHRASE_RES) {
    if (!r.re.test(own)) continue;
    if (r.kind === "quotation_only" && banned.some((b) => b.toLowerCase().includes(r.phrase.toLowerCase()))) continue;
    if (r.kind === "banned") banned.push(r.phrase);
    hits.push({ phrase: r.phrase, kind: r.kind, replacement: r.replacement });
  }
  return hits;
}

// Em dash anywhere, quotations included, for strings that are wholly the
// site's own (titles, labels, slugs' display text).
export function hasEmDash(text) {
  return /—/.test(String(text || ""));
}
'''


def gen_lint():
    with open(os.path.join(CONTENT, "lint-rules.json")) as f:
        rules = json.load(f)
    body = "// Voice lint rules from editorial/lint-rules.json (version " + rules.get("version", "") + ").\n"
    body += "export const LINT_RULES = " + json.dumps(rules, indent=1, ensure_ascii=False) + ";\n"
    body += LINT_FUNCS
    write("lint.js", body)


if __name__ == "__main__":
    gen_content()
    gen_css()
    gen_lint()
    print("generated src/content.js src/css.js src/lint.js")
